# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

desc "Bump build version"
   private_lane :bump_build_version do
      increment_version_code(gradle_file_path: "app/build.gradle.kts")
      # increment_version_name(gradle_file_path: "app/build.gradle.kts")
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Generate new 'Demo Debug' build"
  lane :beta do
    bump_build_version
    gradle(task: "clean assembledemoDebug")
  end

  desc "Generate new 'Full Release' build"
  lane :deploy do
    bump_build_version
    gradle(task: "clean assembleFullRelease")
  end
end
