name: Build App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew lint

      - name: Upload lint result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-html-report
          path: ./app/build/reports/lint-results-demoDebug.html

      - name: Unit test
        run: ./gradlew test

      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-html-report
          path: ./app/build/reports/tests/testdemoDebugUnitTest/index.html

      - name: Install fastlane
        run: bundle install

      - name: Generate 'Demo Debug' build
        run: bundle exec fastlane beta

      - name: Retrieve Version
        id: android_version
        run: echo "VERSION=$(./gradlew -q printVersionInfo)" >> $GITHUB_OUTPUT

      - name: Upload generated APK
        uses: actions/upload-artifact@v3
        with:
          name: demoDebug-${{ steps.android_version.outputs.VERSION }}
          path: ./app/build/outputs/apk/

      - name: Generate 'Full Release' build
        run: bundle exec fastlane deploy

      - name: Upload generated APK
        uses: actions/upload-artifact@v3
        with:
          name: fullRelease
          path: ./app/build/outputs/apk/
