name: Build App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew lint

      - name: Upload lint result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-html-report
          path: ./app/build/reports/lint-results-debug.html

      - name: Unit test
        run: ./gradlew test

      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-html-report
          path: ./app/build/reports/tests/testDebugUnitTest/index.html

      - name: Execute Gradle build
        run: ./gradlew build
